// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnNaVDsyidLS8tJ8ckhlFrugYoiOB2uXc',
    appId: '1:965901105705:web:349ef98a54919e5d813a38',
    messagingSenderId: '965901105705',
    projectId: 'fuely-5b057',
    authDomain: 'fuely-5b057.firebaseapp.com',
    storageBucket: 'fuely-5b057.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKM4pgdScI3Dsou9dYKT0jszt8Bg7GluM',
    appId: '1:965901105705:android:58620cb0a4ed2063813a38',
    messagingSenderId: '965901105705',
    projectId: 'fuely-5b057',
    storageBucket: 'fuely-5b057.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAoccZjAhyZmW3K4-5PUKygKBgDS4VmnY',
    appId: '1:965901105705:ios:3428d2036e7ab3fc813a38',
    messagingSenderId: '965901105705',
    projectId: 'fuely-5b057',
    storageBucket: 'fuely-5b057.firebasestorage.app',
    iosBundleId: 'com.example.trabalhoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAoccZjAhyZmW3K4-5PUKygKBgDS4VmnY',
    appId: '1:965901105705:ios:3428d2036e7ab3fc813a38',
    messagingSenderId: '965901105705',
    projectId: 'fuely-5b057',
    storageBucket: 'fuely-5b057.firebasestorage.app',
    iosBundleId: 'com.example.trabalhoFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnNaVDsyidLS8tJ8ckhlFrugYoiOB2uXc',
    appId: '1:965901105705:web:d0fe2e6ddc0e96f7813a38',
    messagingSenderId: '965901105705',
    projectId: 'fuely-5b057',
    authDomain: 'fuely-5b057.firebaseapp.com',
    storageBucket: 'fuely-5b057.firebasestorage.app',
  );
}
